# -*- coding: utf-8 -*-
"""openCVHOG_svm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tdN8kCZQ-eKojKWwXcWS08lsKIGW7Au_
"""

import cv2
import os
import random
import numpy as np
from PIL import Image
import io
from typing import List, Tuple

from google.colab import drive
drive.mount('/content/drive/')

class ImprovedHOGDetector:
    def __init__(self):
        self.hog = cv2.HOGDescriptor()
        self.hog.setSVMDetector(cv2.HOGDescriptor_getDefaultPeopleDetector())

        self.base_width = 64
        self.base_height = 128
        self.aspect_ratio = self.base_width / self.base_height  # 0.5

    def detect(self, image, params):
        # 1) preprocessing
        if params.get("use_preprocessing", False):
            image = self._preprocess_image(
                image,
                params.get("brightness", 1.0),
                params.get("contrast", 1.0),
                params.get("sharpen", False),
            )

        # 2) multiscale proposals
        boxes, weights = self._detect_multiscale_improved(image, params)
        if len(boxes) == 0:
            return [], []

        # 3) geometry filtering
        boxes, weights = self._filter_boxes(boxes, weights, image.shape, params)
        if len(boxes) == 0:
            return [], []

        # 4) NMS
        boxes, weights = self._improved_nms(boxes, weights, params)
        if len(boxes) == 0:
            return [], []

        # 5) final score filtering
        min_final_score = params.get("min_final_score", 1.0)
        final_boxes, final_weights = [], []
        for b, w in zip(boxes, weights):
            if w >= min_final_score:
                final_boxes.append(b)
                final_weights.append(w)

        return final_boxes, final_weights



    def _detect_multiscale_improved(self, image, params):
        h, w = image.shape[:2]
        all_boxes, all_weights = [], []

        scales = self._calculate_smart_scales(image.shape, params)

        win_stride = params.get("win_stride", (4, 4))
        padding = params.get("padding", (8, 8))
        internal_scale = params.get("internal_scale", 1.10)
        hit_threshold = params.get("hit_threshold", 1.0)

        for scale in scales:
            scaled_h = int(h * scale)
            scaled_w = int(w * scale)

            if scaled_h < 128 or scaled_w < 64:
                continue

            scaled_img = cv2.resize(image, (scaled_w, scaled_h)) if scale != 1.0 else image

            try:
                boxes, weights = self.hog.detectMultiScale(
                    scaled_img,
                    winStride=win_stride,
                    padding=padding,
                    scale=internal_scale,
                    hitThreshold=hit_threshold,
                    useMeanshiftGrouping=False,
                )

                if len(boxes) > 0:
                    boxes = boxes.astype(np.float32)
                    boxes[:, :2] /= scale  # x,y
                    boxes[:, 2:] /= scale  # w,h

                    all_boxes.extend(boxes.tolist())
                    all_weights.extend(weights.flatten().tolist())

            except:
                continue

        return all_boxes, all_weights

    def _calculate_smart_scales(self, img_shape, params):
      min_person_h = params.get("min_person_px", 40)
      max_person_h = params.get("max_person_px", 260)

      # Correct direction:
      # small person -> big scale (upscale)
      # big person -> small scale (downscale)
      min_scale = self.base_height / max_person_h
      max_scale = self.base_height / min_person_h

      num_scales = params.get("num_scales", 10)
      scales = np.logspace(np.log10(min_scale), np.log10(max_scale), num=num_scales)

      # Optional: detect small people first (usually helps)
      scales = np.sort(scales)[::-1]

      return scales.tolist()


    def _filter_boxes(self, boxes, weights, img_shape, params):
        boxes = np.array(boxes, dtype=np.float32)
        weights = np.array(weights, dtype=np.float32)

        h, w = img_shape[:2]

        bw = boxes[:, 2]
        bh = boxes[:, 3]
        areas = bw * bh
        aspect = bw / (bh + 1e-6)

        min_area = params.get("min_box_area", 1200)
        max_area = params.get("max_box_area", None)
        if max_area is None:
            max_area = w * h * 0.30

        min_aspect = params.get("min_aspect_ratio", 0.35)
        max_aspect = params.get("max_aspect_ratio", 0.70)

        valid = (
            (areas >= min_area) &
            (areas <= max_area) &
            (aspect >= min_aspect) &
            (aspect <= max_aspect) &
            (boxes[:, 0] >= 0) &
            (boxes[:, 1] >= 0) &
            (boxes[:, 0] + boxes[:, 2] <= w) &
            (boxes[:, 1] + boxes[:, 3] <= h)
        )

        return boxes[valid].tolist(), weights[valid].tolist()

    def _improved_nms(self, boxes, weights, params):
        if len(boxes) == 0:
            return [], []

        boxes = np.array(boxes, dtype=np.float32)
        weights = np.array(weights, dtype=np.float32)

        x1 = boxes[:, 0]
        y1 = boxes[:, 1]
        x2 = boxes[:, 0] + boxes[:, 2]
        y2 = boxes[:, 1] + boxes[:, 3]
        areas = boxes[:, 2] * boxes[:, 3]

        aspect = boxes[:, 2] / (boxes[:, 3] + 1e-6)
        aspect_bonus = 1.0 - np.abs(aspect - self.aspect_ratio)
        adjusted = weights * (1.0 + 0.2 * aspect_bonus)

        order = np.argsort(adjusted)[::-1]
        keep = []
        thr = params.get("nms_threshold", 0.12)

        while len(order) > 0:
            i = order[0]
            keep.append(i)
            if len(order) == 1:
                break

            xx1 = np.maximum(x1[i], x1[order[1:]])
            yy1 = np.maximum(y1[i], y1[order[1:]])
            xx2 = np.minimum(x2[i], x2[order[1:]])
            yy2 = np.minimum(y2[i], y2[order[1:]])

            w_ov = np.maximum(0, xx2 - xx1)
            h_ov = np.maximum(0, yy2 - yy1)
            inter = w_ov * h_ov

            union = areas[i] + areas[order[1:]] - inter
            iou = inter / (union + 1e-6)

            order = order[1:][iou <= thr]

        return boxes[keep].tolist(), weights[keep].tolist()

    def _preprocess_image(self, image, brightness, contrast, sharpen):
        processed = image.copy()

        if brightness != 1.0 or contrast != 1.0:
            processed = cv2.convertScaleAbs(
                processed, alpha=contrast, beta=(brightness - 1.0) * 50
            )

        if sharpen:
            kernel = np.array([[-1,-1,-1], [-1,9,-1], [-1,-1,-1]])
            processed = cv2.filter2D(processed, -1, kernel)

        return processed

    def _detect_pipeline(self, image, params):
        all_boxes, all_weights = self._detect_multiscale_improved(image, params)

        if len(all_boxes) == 0:
          return [], []

        filtered_boxes, filtered_weights = self._filter_boxes(
            all_boxes, all_weights, image.shape, params
        )

        if len(filtered_boxes) == 0:
            return [], []

        nms_boxes, nms_weights = self._improved_nms(
            filtered_boxes, filtered_weights, params
        )

        return nms_boxes, nms_weights

    def visualize(self, image, boxes, weights):
        result = image.copy()

        # Draw boxes with color based on confidence
        for i, (box, weight) in enumerate(zip(boxes, weights)):
            x, y, w, h = [int(v) for v in box]

            # Color based on confidence (green = high, yellow = medium, red = low)
            if weight > 1.5:
                color = (0, 255, 0)  # Green
            elif weight > 0.8:
                color = (0, 255, 255)  # Yellow
            else:
                color = (0, 165, 255)  # Orange

            cv2.rectangle(result, (x, y), (x + w, y + h), color, 2)

            # Label with confidence
            label = f"{weight:.2f}"
            label_size, _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.5, 1)
            cv2.rectangle(
                result, (x, y - label_size[1] - 4), (x + label_size[0], y), color, -1
            )
            cv2.putText(
                result, label, (x, y - 2), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1
            )

        # Statistics overlay
        num_people = len(boxes)
        h, w = image.shape[:2]
        density = num_people / ((w * h) / 1_000_000)

        if density < 5:
            crowd_level = "Low"
            level_color = (0, 255, 0)
        elif density < 15:
            crowd_level = "Medium"
            level_color = (0, 255, 255)
        elif density < 30:
            crowd_level = "High"
            level_color = (0, 165, 255)
        else:
            crowd_level = "Very High"
            level_color = (0, 0, 255)

        cv2.putText(
            result,
            f"People: {num_people}",
            (15, 30),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            (255, 255, 255),
            2,
        )
        cv2.putText(
            result,
            f"Crowd: {crowd_level}",
            (15, 60),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            level_color,
            2,
        )
        cv2.putText(
            result,
            f"Density: {density:.1f}/100k",
            (15, 90),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            (255, 255, 255),
            2,
        )

        return result

params_strong = {
    "use_preprocessing": True,
    "brightness": 1.1,
    "contrast": 1.2,
    "sharpen": True,

    "win_stride": (4, 4),
    "padding": (8, 8),

    "internal_scale": 1.05,
    "hit_threshold": 0.05,
    "min_final_score": 0.05,

    "min_person_px": 40,
    "max_person_px": 220,
    "num_scales": 8,

    "min_box_area": 1500,
    "max_box_area": None,

    "min_aspect_ratio": 0.35,
    "max_aspect_ratio": 0.65,

    "nms_threshold": 0.4,
}

params_weak = params_strong.copy()
params_weak.update({
    "internal_scale": 1.05,
    "num_scales": 8,
    "min_person_px": 28,
    "min_final_score": 0.45,
    "nms_threshold": 0.4,
})

def dual_pass_detect(detector, image, params_strong, params_weak):
    # Make copies so we can temporarily disable filtering inside detect()
    ps = params_strong.copy()
    pw = params_weak.copy()

    # Disable per-pass final filtering (keep everything after NMS)
    ps["min_final_score"] = -999
    pw["min_final_score"] = -999

    boxes_s, weights_s = detector.detect(image, ps)
    boxes_w, weights_w = detector.detect(image, pw)

    all_boxes = boxes_s + boxes_w
    all_weights = weights_s + weights_w

    # Final NMS
    final_boxes, final_weights = detector._improved_nms(all_boxes, all_weights, params_strong)

    final_min_score = params_weak.get("min_final_score", 0.35)
    clean_boxes, clean_weights = [], []
    for b, w in zip(final_boxes, final_weights):
        if w >= final_min_score:
            clean_boxes.append(b)
            clean_weights.append(w)

    return clean_boxes, clean_weights

def estimate_crowd_density(boxes, image_shape):
    h, w = image_shape[:2]
    image_area = w * h

    total_person_area = 0
    for (_, _, bw, bh) in boxes:
        total_person_area += bw * bh

    density_ratio = total_person_area / image_area

    # heuristic mapping
    if density_ratio < 0.02:
        level = "Low"
    elif density_ratio < 0.05:
        level = "Medium"
    elif density_ratio < 0.08:
        level = "High"
    else:
        level = "Very High"

    return density_ratio, level

import os
import pickle

def save_hog_config(pkl_path, params_strong, params_weak):
    os.makedirs(os.path.dirname(pkl_path), exist_ok=True)
    payload = {"params_strong": params_strong, "params_weak": params_weak}
    with open(pkl_path, "wb") as f:
        pickle.dump(payload, f)
    print("Saved:", pkl_path)

def load_hog_config(pkl_path):
    with open(pkl_path, "rb") as f:
        payload = pickle.load(f)
    return payload["params_strong"], payload["params_weak"]

MODEL_DIR = "/content/drive/MyDrive/fpcomvis/model_hog"
CFG_PATH = os.path.join(MODEL_DIR, "opencv_hog.pkl")

save_hog_config(CFG_PATH, params_strong, params_weak)
params_strong2, params_weak2 = load_hog_config(CFG_PATH)

from google.colab.patches import cv2_imshow

import cv2
from google.colab.patches import cv2_imshow

img_path = "/content/seq_001959.jpg"

image = cv2.imread(img_path)
assert image is not None, "Gambar gagal dibaca"

detector = ImprovedHOGDetector()
boxes, weights = dual_pass_detect(detector, image, params_strong, params_weak)

vis = image.copy()
for (x,y,w,h), s in zip(boxes, weights):
    x,y,w,h = map(int, [x,y,w,h])
    cv2.rectangle(vis, (x,y), (x+w, y+h), (0,255,0), 2)
    cv2.putText(vis, f"{s:.2f}", (x, max(0,y-5)),
                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,255,0), 1)

print("Total boxes:", len(boxes))
cv2_imshow(vis)