# -*- coding: utf-8 -*-
"""HOG_SIFT_CrowdDetection2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hM2AgGwoHaeqABRmKuAooUdFT8jGwVBE
"""

!pip install scikit-image scikit-learn opencv-python opencv-contrib-python matplotlib Pillow scipy tqdm albumentations -q

import numpy as np
import cv2
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from skimage.feature import hog
from skimage import exposure
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
import os
import pickle
from tqdm import tqdm
import warnings
from glob import glob
import random
import albumentations as A

warnings.filterwarnings('ignore')

print("✓ Libraries imported successfully!")
print(f"OpenCV version: {cv2.__version__}")

from google.colab import drive
drive.mount('/content/drive')
print("✓ Google Drive mounted successfully!")

BASE_DIR = '/content/drive/MyDrive/crowd_body_detection'

# Dataset paths
POSITIVE_SAMPLES_DIR = f'{BASE_DIR}/data/positive_samples'
NEGATIVE_SAMPLES_DIR = f'{BASE_DIR}/data/negative_samples'
MODEL_DIR = f'{BASE_DIR}/models_sift_openCV'

BASE_DIR = '/content/drive/MyDrive/crowd_body_detection'

# Dataset paths
POSITIVE_SAMPLES_DIR = f'{BASE_DIR}/data/positive_samples'
NEGATIVE_SAMPLES_DIR = f'{BASE_DIR}/data/negative_samples'
MODEL_DIR = f'{BASE_DIR}/models_sift'

# Image dimensions
BODY_WIDTH = 64
BODY_HEIGHT = 128
TARGET_SIZE = (BODY_WIDTH, BODY_HEIGHT)

# HOG parameters
HOG_ORIENTATIONS = 9
HOG_PIXELS_PER_CELL = (8, 8)
HOG_CELLS_PER_BLOCK = (2, 2)

# SIFT parameters
SIFT_GRID_SIZE = (4, 8)
SIFT_DESCRIPTOR_SIZE = 128

# Detection parameters
WINDOW_SIZE = TARGET_SIZE
STEP_SIZE = 8
SCALE_FACTOR = 1.2
MIN_CONFIDENCE = 0.5
NMS_THRESHOLD = 0.3

# Data augmentation parameters
TARGET_SAMPLES = 5000
AUGMENTATION_PER_IMAGE = 5

# Create model directory
os.makedirs(MODEL_DIR, exist_ok=True)

print("✓ Configuration completed!")
print(f"  Target size: {TARGET_SIZE}")
print(f"  Target samples per class: {TARGET_SAMPLES}")
print(f"  HOG config: {HOG_ORIENTATIONS} orientations, {HOG_PIXELS_PER_CELL} pixels/cell")
print(f"  SIFT config: Dense grid {SIFT_GRID_SIZE}")

def create_augmentation_pipeline():
    transform = A.Compose([
        A.OneOf([
            A.HorizontalFlip(p=1.0),
            A.RandomBrightnessContrast(brightness_limit=0.2, contrast_limit=0.2, p=1.0),
            A.GaussNoise(var_limit=(10.0, 50.0), p=1.0),
            A.GaussianBlur(blur_limit=(3, 5), p=1.0),
            A.RandomGamma(gamma_limit=(80, 120), p=1.0),
        ], p=1.0),
        A.ShiftScaleRotate(
            shift_limit=0.1,
            scale_limit=0.1,
            rotate_limit=10,
            border_mode=cv2.BORDER_CONSTANT,
            value=0,
            p=0.5
        ),
    ])
    return transform

def augment_image(image, transform):
    # Albumentations expects RGB format
    if len(image.shape) == 2:
        image = cv2.cvtColor(image, cv2.COLOR_GRAY2RGB)
    elif image.shape[2] == 3:
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    augmented = transform(image=image)['image']

    # Convert back to BGR for OpenCV
    augmented = cv2.cvtColor(augmented, cv2.COLOR_RGB2BGR)

    return augmented

def augment_positive_samples(positive_samples, target_count, aug_per_image=5):
    print(f"\nAugmenting positive samples from {len(positive_samples)} to {target_count}...")

    transform = create_augmentation_pipeline()
    augmented_samples = list(positive_samples.copy())

    original_count = len(positive_samples)
    needed_augmentations = target_count - original_count

    if needed_augmentations <= 0:
        print("No augmentation needed - already have enough samples")
        return np.array(positive_samples[:target_count])

    # Calculate how many times we need to go through the dataset
    cycles_needed = (needed_augmentations // original_count) + 1

    print(f"  Original samples: {original_count}")
    print(f"  Needed augmentations: {needed_augmentations}")
    print(f"  Augmentation cycles: {cycles_needed}")

    with tqdm(total=needed_augmentations, desc="Augmenting") as pbar:
        for cycle in range(cycles_needed):
            # Shuffle for variety
            indices = list(range(original_count))
            random.shuffle(indices)

            for idx in indices:
                if len(augmented_samples) >= target_count:
                    break

                # Apply augmentation
                aug_image = augment_image(positive_samples[idx], transform)
                augmented_samples.append(aug_image)
                pbar.update(1)

            if len(augmented_samples) >= target_count:
                break

    # Trim to exact target count
    augmented_samples = augmented_samples[:target_count]

    print(f"✓ Augmentation complete: {len(augmented_samples)} total positive samples")

    return np.array(augmented_samples)

print("✓ Data augmentation functions defined!")

def load_samples_from_directories(pos_dir, neg_dir, max_samples=None):

    print("\nLoading samples from directories...")

    positive_samples = []
    negative_samples = []

    # Get file lists
    pos_files = glob(os.path.join(pos_dir, '*.*'))
    neg_files = glob(os.path.join(neg_dir, '*.*'))

    # Shuffle file lists
    random.seed(42)
    random.shuffle(pos_files)
    random.shuffle(neg_files)

    print(f"  Found {len(pos_files)} positive files")
    print(f"  Found {len(neg_files)} negative files")

    # Load positive samples
    for img_path in tqdm(pos_files, desc="Loading positive samples"):
        img = cv2.imread(img_path)
        if img is not None:
            positive_samples.append(img)

    # Load negative samples (limit to target count)
    if max_samples and len(neg_files) > max_samples:
        neg_files = neg_files[:max_samples]

    for img_path in tqdm(neg_files, desc="Loading negative samples"):
        img = cv2.imread(img_path)
        if img is not None:
            negative_samples.append(img)

    print(f"✓ Loaded {len(positive_samples)} positive and {len(negative_samples)} negative samples")

    return np.array(positive_samples), np.array(negative_samples)

def visualize_samples(positive_samples, negative_samples, num_samples=10):
    fig, axes = plt.subplots(2, num_samples, figsize=(20, 5))

    # Show positive samples
    for i in range(min(num_samples, len(positive_samples))):
        img = cv2.cvtColor(positive_samples[i], cv2.COLOR_BGR2RGB)
        axes[0, i].imshow(img)
        axes[0, i].set_title('Positive', fontsize=10)
        axes[0, i].axis('off')

    # Show negative samples
    for i in range(min(num_samples, len(negative_samples))):
        img = cv2.cvtColor(negative_samples[i], cv2.COLOR_BGR2RGB)
        axes[1, i].imshow(img)
        axes[1, i].set_title('Negative', fontsize=10)
        axes[1, i].axis('off')

    plt.suptitle('Training Samples Preview', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.show()

def visualize_augmentation(original_image, augmented_images, num_show=6):
    num_show = min(num_show, len(augmented_images))
    fig, axes = plt.subplots(1, num_show + 1, figsize=(20, 4))

    # Show original
    img = cv2.cvtColor(original_image, cv2.COLOR_BGR2RGB)
    axes[0].imshow(img)
    axes[0].set_title('Original', fontsize=12, fontweight='bold')
    axes[0].axis('off')

    # Show augmented versions
    for i in range(num_show):
        img = cv2.cvtColor(augmented_images[i], cv2.COLOR_BGR2RGB)
        axes[i + 1].imshow(img)
        axes[i + 1].set_title(f'Augmented {i+1}', fontsize=10)
        axes[i + 1].axis('off')

    plt.suptitle('Data Augmentation Examples', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.show()

print("✓ Data loading functions defined!")

positive_samples, negative_samples = load_samples_from_directories(
    POSITIVE_SAMPLES_DIR,
    NEGATIVE_SAMPLES_DIR,
    max_samples=None  # Load all available samples
)


print("\n" + "="*60)
print("ORIGINAL DATASET")
print("="*60)
visualize_samples(positive_samples, negative_samples, num_samples=10)

print("\n" + "="*60)
print("AUGMENTATION DEMONSTRATION")
print("="*60)
if len(positive_samples) > 0:
    # Create augmented versions of first positive sample
    transform = create_augmentation_pipeline()
    demo_augmented = [augment_image(positive_samples[0], transform) for _ in range(6)]
    visualize_augmentation(positive_samples[0], demo_augmented, num_show=6)

# Augment positive samples to target count
positive_samples_augmented = augment_positive_samples(
    positive_samples,
    TARGET_SAMPLES,
    aug_per_image=AUGMENTATION_PER_IMAGE
)

# Balance negative samples to match positive count
print(f"\nBalancing negative samples to {TARGET_SAMPLES}...")
if len(negative_samples) > TARGET_SAMPLES:
    # Randomly sample if we have too many
    indices = np.random.choice(len(negative_samples), TARGET_SAMPLES, replace=False)
    negative_samples_balanced = negative_samples[indices]
    print(f"  Sampled {TARGET_SAMPLES} from {len(negative_samples)} negative samples")
elif len(negative_samples) < TARGET_SAMPLES:
    # If we need more, duplicate with slight variations
    print(f"  Warning: Only {len(negative_samples)} negative samples available")
    print(f"  Creating duplicates to reach {TARGET_SAMPLES} samples...")

    needed = TARGET_SAMPLES - len(negative_samples)
    indices = np.random.choice(len(negative_samples), needed, replace=True)
    duplicates = negative_samples[indices]
    negative_samples_balanced = np.concatenate([negative_samples, duplicates])
else:
    negative_samples_balanced = negative_samples

print(f"✓ Balanced negative samples: {len(negative_samples_balanced)}")

# Final dataset summary
print("\n" + "="*60)
print("FINAL BALANCED DATASET")
print("="*60)
print(f"  Positive samples: {len(positive_samples_augmented)}")
print(f"  Negative samples: {len(negative_samples_balanced)}")
print(f"  Total samples: {len(positive_samples_augmented) + len(negative_samples_balanced)}")
print(f"  Balance ratio: 1:1")

# Visualize final balanced dataset
visualize_samples(positive_samples_augmented, negative_samples_balanced, num_samples=10)

def extract_hog_features(image):

    if len(image.shape) == 3:
        image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Resize to target size
    image = cv2.resize(image, TARGET_SIZE)

    # Extract HOG features
    hog_features = hog(
        image,
        orientations=HOG_ORIENTATIONS,
        pixels_per_cell=HOG_PIXELS_PER_CELL,
        cells_per_block=HOG_CELLS_PER_BLOCK,
        block_norm='L2-Hys',
        visualize=False,
        feature_vector=True
    )

    return hog_features

def extract_dense_sift_features(image, grid_size=SIFT_GRID_SIZE):
    """
    Extract dense SIFT features on a regular grid
    """
    if len(image.shape) == 3:
        image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Resize to target size
    image = cv2.resize(image, TARGET_SIZE)

    # Initialize SIFT
    sift = cv2.SIFT_create()

    # Calculate grid step
    h, w = image.shape
    step_x = w // grid_size[0]
    step_y = h // grid_size[1]

    # Create keypoints on a grid
    keypoints = []
    for i in range(grid_size[0]):
        for j in range(grid_size[1]):
            x = step_x * i + step_x // 2
            y = step_y * j + step_y // 2
            keypoints.append(cv2.KeyPoint(x, y, step_x))

    # Compute SIFT descriptors at keypoints
    _, descriptors = sift.compute(image, keypoints)

    # Handle case where descriptors might be None
    if descriptors is None:
        descriptors = np.zeros((grid_size[0] * grid_size[1], SIFT_DESCRIPTOR_SIZE))

    # Flatten the descriptors
    sift_features = descriptors.flatten()

    return sift_features

def extract_fused_features(image):
    # Extract HOG features
    hog_features = extract_hog_features(image)

    # Extract SIFT features
    sift_features = extract_dense_sift_features(image)

    # Concatenate features
    fused_features = np.concatenate([hog_features, sift_features])

    return fused_features

print("✓ Feature extraction functions defined!")

# Test feature extraction
test_img = np.random.randint(0, 255, (128, 64, 3), dtype=np.uint8)
hog_feat = extract_hog_features(test_img)
sift_feat = extract_dense_sift_features(test_img)
fused_feat = extract_fused_features(test_img)

print(f"  HOG feature dimension: {len(hog_feat)}")
print(f"  SIFT feature dimension: {len(sift_feat)}")
print(f"  Fused feature dimension: {len(fused_feat)}")

def prepare_training_data(positive_samples, negative_samples):
    """
    Extract features from all samples and create training dataset
    """
    print("\nExtracting features from training data...")

    X = []
    y = []

    # Extract features from positive samples
    for img in tqdm(positive_samples, desc="Processing positive samples"):
        features = extract_fused_features(img)
        X.append(features)
        y.append(1)  # Positive label

    # Extract features from negative samples
    for img in tqdm(negative_samples, desc="Processing negative samples"):
        features = extract_fused_features(img)
        X.append(features)
        y.append(0)  # Negative label

    X = np.array(X)
    y = np.array(y)

    print(f"\n✓ Feature extraction complete!")
    print(f"  Feature matrix shape: {X.shape}")
    print(f"  Labels shape: {y.shape}")
    print(f"  Positive samples: {np.sum(y == 1)}")
    print(f"  Negative samples: {np.sum(y == 0)}")
    print(f"  Class balance: {np.sum(y == 1) / len(y) * 100:.1f}% positive")

    return X, y

# Extract features from balanced dataset
X, y = prepare_training_data(positive_samples_augmented, negative_samples_balanced)

def train_svm_classifier(X, y, test_size=0.2, random_state=42):
    """
    Train SVM classifier with feature scaling
    """
    print("\n" + "="*60)
    print("TRAINING SVM CLASSIFIER")
    print("="*60)

    # Split data
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=random_state, stratify=y
    )

    print(f"  Training samples: {len(X_train)}")
    print(f"  Test samples: {len(X_test)}")
    print(f"  Feature dimension: {X_train.shape[1]}")

    # Create pipeline with scaler and SVM
    pipeline = Pipeline([
        ('scaler', StandardScaler()),
        ('svm', LinearSVC(C=1.0, max_iter=10000, dual=False, random_state=random_state))
    ])

    # Train
    print("\nTraining SVM...")
    pipeline.fit(X_train, y_train)

    # Evaluate on training set
    y_train_pred = pipeline.predict(X_train)
    train_accuracy = accuracy_score(y_train, y_train_pred)

    # Evaluate on test set
    y_test_pred = pipeline.predict(X_test)
    test_accuracy = accuracy_score(y_test, y_test_pred)

    print(f"\n✓ Training complete!")
    print(f"  Training accuracy: {train_accuracy * 100:.2f}%")
    print(f"  Test accuracy: {test_accuracy * 100:.2f}%")

    # Detailed classification report
    print("\n" + "="*60)
    print("CLASSIFICATION REPORT (Test Set)")
    print("="*60)
    print(classification_report(y_test, y_test_pred,
                                target_names=['Negative', 'Positive'],
                                digits=4))

    # Confusion matrix
    print("="*60)
    print("CONFUSION MATRIX (Test Set)")
    print("="*60)
    cm = confusion_matrix(y_test, y_test_pred)
    print(cm)
    print(f"\nTrue Negatives:  {cm[0,0]}")
    print(f"False Positives: {cm[0,1]}")
    print(f"False Negatives: {cm[1,0]}")
    print(f"True Positives:  {cm[1,1]}")

    # Visualize confusion matrix
    plt.figure(figsize=(8, 6))
    plt.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues)
    plt.title('Confusion Matrix', fontsize=16, fontweight='bold')
    plt.colorbar()
    tick_marks = np.arange(2)
    plt.xticks(tick_marks, ['Negative', 'Positive'], fontsize=12)
    plt.yticks(tick_marks, ['Negative', 'Positive'], fontsize=12)

    # Add text annotations
    thresh = cm.max() / 2.
    for i, j in np.ndindex(cm.shape):
        plt.text(j, i, format(cm[i, j], 'd'),
                ha="center", va="center",
                color="white" if cm[i, j] > thresh else "black",
                fontsize=20, fontweight='bold')

    plt.ylabel('True Label', fontsize=14)
    plt.xlabel('Predicted Label', fontsize=14)
    plt.tight_layout()
    plt.show()

    return pipeline, (X_train, X_test, y_train, y_test)

# Train the model
model_pipeline, (X_train, X_test, y_train, y_test) = train_svm_classifier(X, y)

def save_model(model, model_path):

    print(f"\nSaving model to: {model_path}")
    with open(model_path, 'wb') as f:
        pickle.dump(model, f)
    print("✓ Model saved successfully!")

def load_model(model_path):

    print(f"\nLoading model from: {model_path}")
    with open(model_path, 'rb') as f:
        model = pickle.load(f)
    print("✓ Model loaded successfully!")
    return model

# Save the trained model
model_path = os.path.join(MODEL_DIR, 'hog_sift_svm_model_balanced.pkl')
save_model(model_pipeline, model_path)

def sliding_window(image, window_size, step_size):

    for y in range(0, image.shape[0] - window_size[1], step_size):
        for x in range(0, image.shape[1] - window_size[0], step_size):
            yield (x, y, image[y:y + window_size[1], x:x + window_size[0]])

def pyramid(image, scale=1.2, min_size=(64, 128)):

    yield image, 1.0

    current_scale = 1.0
    while True:
        current_scale /= scale
        h, w = image.shape[:2]
        new_h, new_w = int(h * current_scale), int(w * current_scale)

        if new_w < min_size[0] or new_h < min_size[1]:
            break

        scaled = cv2.resize(image, (new_w, new_h))
        yield scaled, current_scale

def non_max_suppression(boxes, scores, threshold=0.3):
    """
    Apply Non-Maximum Suppression to remove overlapping detections
    """
    if len(boxes) == 0:
        return []

    boxes = np.array(boxes)
    scores = np.array(scores)

    x1 = boxes[:, 0]
    y1 = boxes[:, 1]
    x2 = boxes[:, 0] + boxes[:, 2]
    y2 = boxes[:, 1] + boxes[:, 3]

    areas = (x2 - x1) * (y2 - y1)
    order = scores.argsort()[::-1]

    keep = []
    while order.size > 0:
        i = order[0]
        keep.append(i)

        xx1 = np.maximum(x1[i], x1[order[1:]])
        yy1 = np.maximum(y1[i], y1[order[1:]])
        xx2 = np.minimum(x2[i], x2[order[1:]])
        yy2 = np.minimum(y2[i], y2[order[1:]])

        w = np.maximum(0.0, xx2 - xx1)
        h = np.maximum(0.0, yy2 - yy1)
        inter = w * h

        union = areas[i] + areas[order[1:]] - inter
        iou = inter / union

        inds = np.where(iou <= threshold)[0]
        order = order[inds + 1]

    return keep

def detect_people(image, model, window_size=WINDOW_SIZE, step_size=STEP_SIZE,
                 scale_factor=SCALE_FACTOR, min_confidence=MIN_CONFIDENCE,
                 nms_threshold=NMS_THRESHOLD, show_progress=True):
    """
    Detect people in an image using sliding window and image pyramid
    """
    detections = []
    total_windows = 0

    if show_progress:
        print("Running detection...")

    # Create image pyramid
    for scale_idx, (scaled_img, scale) in enumerate(pyramid(image, scale=scale_factor, min_size=window_size)):
        if show_progress:
            print(f"  Scale {scale_idx+1}: {scaled_img.shape[1]}x{scaled_img.shape[0]} (factor: {scale:.3f})", end='')

        windows_at_scale = 0

        # Slide window across image
        for (x, y, window) in sliding_window(scaled_img, window_size, step_size):
            # Check if window is the correct size
            if window.shape[0] != window_size[1] or window.shape[1] != window_size[0]:
                continue

            windows_at_scale += 1
            total_windows += 1

            # Extract features
            features = extract_fused_features(window)
            features = features.reshape(1, -1)

            # Predict
            prediction = model.predict(features)[0]

            if prediction == 1:
                # Get decision function score
                score = model.decision_function(features)[0]

                if score >= min_confidence:
                    # Scale coordinates back to original image
                    orig_x = int(x / scale)
                    orig_y = int(y / scale)
                    orig_w = int(window_size[0] / scale)
                    orig_h = int(window_size[1] / scale)

                    detections.append([orig_x, orig_y, orig_w, orig_h, score])

        if show_progress:
            print(f" - {windows_at_scale} windows checked")

    if show_progress:
        print(f"\n  Total windows checked: {total_windows}")
        print(f"  Raw detections before NMS: {len(detections)}")

    # Apply Non-Maximum Suppression
    if len(detections) > 0:
        detections = np.array(detections)
        boxes = detections[:, :4]
        scores = detections[:, 4]

        keep = non_max_suppression(boxes, scores, threshold=nms_threshold)
        detections = detections[keep]

        if show_progress:
            print(f"  Final detections after NMS: {len(detections)}")

    return detections

def visualize_detections(image, detections, title="Detections"):

    # Convert BGR to RGB for display
    img_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    fig, ax = plt.subplots(1, figsize=(15, 10))
    ax.imshow(img_rgb)

    # Draw bounding boxes
    for detection in detections:
        x, y, w, h, score = detection
        rect = patches.Rectangle(
            (x, y), w, h,
            linewidth=2,
            edgecolor='lime',
            facecolor='none'
        )
        ax.add_patch(rect)

        # Add confidence score
        ax.text(x, y - 5, f'{score:.2f}',
               bbox=dict(boxstyle='round', facecolor='lime', alpha=0.8),
               fontsize=10, color='black', fontweight='bold')

    ax.set_title(f"{title} - {len(detections)} people detected", fontsize=16, fontweight='bold')
    ax.axis('off')
    plt.tight_layout()
    plt.show()

print("✓ Detection functions defined!")

test_image_path = '/content/drive/MyDrive/crowd_body_detection/data/test_images/seq_001959.jpg'

if os.path.exists(test_image_path):
    print("\n" + "="*60)
    print("TESTING CROWD DETECTION")
    print("="*60)

    test_img = cv2.imread(test_image_path)

    if test_img is None:
        print("Error: Image failed to load")
    else:
        print(f"Image loaded: {test_img.shape[1]}x{test_img.shape[0]} pixels\n")

        # Run detection
        detections = detect_people(
            test_img,
            model_pipeline,
            step_size=STEP_SIZE,
            min_confidence=3.8,
            nms_threshold=0.25
        )

        # Copy image for drawing
        result = test_img.copy()

        # Draw bounding boxes
        for det in detections:
            x, y, w, h, score = det
            x, y, w, h = int(x), int(y), int(w), int(h)

            cv2.rectangle(
                result,
                (x, y),
                (x + w, y + h),
                (0, 255, 0),
                2
            )

            cv2.putText(
                result,
                f"{score:.2f}",
                (x, max(y - 5, 10)),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.5,
                (0, 255, 0),
                1
            )

        # Calculate crowd metrics
        num_people = len(detections)
        h_img, w_img = result.shape[:2]
        density = (num_people / (w_img * h_img)) * 100000

        if density < 5:
            crowd_level = "Low"
        elif density < 15:
            crowd_level = "Medium"
        elif density < 30:
            crowd_level = "High"
        else:
            crowd_level = "Very High"

        # Add text overlay
        cv2.putText(result, f"People: {num_people}", (10, 30),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
        cv2.putText(result, f"Crowd: {crowd_level}", (10, 65),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
        cv2.putText(result, f"Density: {density:.2f}", (10, 100),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)

        # Display result
        plt.figure(figsize=(14, 9))
        plt.imshow(cv2.cvtColor(result, cv2.COLOR_BGR2RGB))
        plt.title("HOG + SIFT Crowd Detection (Balanced Dataset)", fontsize=16, fontweight='bold')
        plt.axis("off")
        plt.tight_layout()
        plt.show()

        print(f"\n✓ Detection complete!")
        print(f"  People detected: {num_people}")
        print(f"  Crowd level: {crowd_level}")
        print(f"  Density: {density:.2f}")
else:
    print(f"\nWarning: Test image not found at: {test_image_path}")
    print("Please update the path or add a test image")